const heicConvert = require('heic-convert')
const { readFileSync, writeFileSync } = require('fs')
;(async()=>{
  const buf = readFileSync('/sessions/loving-keen-dijkstra/mnt/uploads/IMG_4084.HEIC')
  const out = await heicConvert({ buffer: buf, format:'JPEG', quality:0.95 })
  const jpeg = Buffer.from(out)
  console.log('heic-convert JPEG:', (jpeg.length/1024).toFixed(0)+'KB')
  const Jimp = require('jimp')
  console.log('jimp keys:', typeof Jimp, typeof Jimp.read, typeof Jimp.MIME_JPEG, Jimp.MIME_JPEG)
  const image = await Jimp.read(jpeg)
  console.log('read ok', image.bitmap.width+'x'+image.bitmap.height)
  if (Math.max(image.bitmap.width, image.bitmap.height) > 2560) image.scaleToFit(2560,2560)
  image.quality(90)
  const o = await image.getBufferAsync(Jimp.MIME_JPEG)
  console.log('jimp out:', (o.length/1024).toFixed(0)+'KB', image.bitmap.width+'x'+image.bitmap.height)
  writeFileSync('/sessions/loving-keen-dijkstra/mnt/outputs/pipe_4084.jpg', o)
})().catch(e=>{ console.log('PIPELINE ERROR:', e && e.message); console.log(e && e.stack) })
