const heicConvert = require('heic-convert')
const { readFileSync, writeFileSync } = require('fs')
;(async()=>{
  const buf = readFileSync('/sessions/loving-keen-dijkstra/mnt/uploads/IMG_4084.HEIC')
  const jpeg = Buffer.from(await heicConvert({ buffer: buf, format:'JPEG', quality:0.95 }))
  console.log('heic-convert JPEG:', (jpeg.length/1024).toFixed(0)+'KB')
  const Jimp = require('jimp')
  const jpegjs = require('jpeg-js')
  // Raise jpeg-js limits so it can decode large (24MP) phone images.
  Jimp.decoders['image/jpeg'] = (data) => jpegjs.decode(data, { maxMemoryUsageInMB: 1024, maxResolutionInMP: 200 })
  const t=Date.now()
  const image = await Jimp.read(jpeg)
  console.log('read ok', image.bitmap.width+'x'+image.bitmap.height, (Date.now()-t)+'ms')
  if (Math.max(image.bitmap.width, image.bitmap.height) > 2560) image.scaleToFit(2560,2560)
  image.quality(90)
  const o = await image.getBufferAsync(Jimp.MIME_JPEG)
  console.log('FINAL:', (o.length/1024).toFixed(0)+'KB', image.bitmap.width+'x'+image.bitmap.height, 'total '+(Date.now()-t)+'ms')
  writeFileSync('/sessions/loving-keen-dijkstra/mnt/outputs/pipe2_4084.jpg', o)
})().catch(e=>{ console.log('ERROR:', e && e.message) })
